### ISSUE TITLE
Demo's not working

### ISSUE THREAD

**Issue by birkhofflee** [InventivetalentDev/mcauth.ga#1]
As the title says.

**Comment by InventivetalentDev** [comment]
Oh great, I totally know what's wrong now! /sarcasm  

Please provide more information about what's not working for you.

**Comment by InventivetalentDev** [comment]
Looks like the website stored your IPv6 address while the server received an IPv4 address when you logged in. Please make sure you're not obfuscating your IP.

**Comment by birkhofflee** [comment]
I did NOT obfuscate my IP. I directly connected to both he website and the MC server.

Best regards,
Birkhoff Lee
